spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080